### ISSUE TITLE
No launcher (icon_path fall back to None?)

### ISSUE THREAD

**Issue by MarkGhanz** [linkfrg/dotfiles#15]
In app.py:
```
Traceback (most recent call last):
  File "/home/ghanz/.config/eww/scripts/apps.py", line 125, in <module>
    entries = get_desktop_entries()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghanz/.config/eww/scripts/apps.py", line 37, in get_desktop_entries
    icon_path = get_gtk_icon(parser.get("Desktop Entry", "Icon", fallback=None))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghanz/.config/eww/scripts/apps.py", line 20, in get_gtk_icon
    icon_info = theme.lookup_icon(icon_name, 128, 0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 1 does not allow None as a value
 2024-01-10T03:23:15.043Z INFO  eww::app                > Closing gtk window launcher

Traceback (most recent call last):
  File "/home/ghanz/.config/eww/scripts/apps.py", line 125, in <module>
    entries = get_desktop_entries()
              ^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghanz/.config/eww/scripts/apps.py", line 37, in get_desktop_entries
    icon_path = get_gtk_icon(parser.get("Desktop Entry", "Icon", fallback=None))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ghanz/.config/eww/scripts/apps.py", line 20, in get_gtk_icon
    icon_info = theme.lookup_icon(icon_name, 128, 0)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Argument 1 does not allow None as a value
```

**Comment by MarkGhanz** [comment]
OK I know where the problem is. I have an app "VRRTest", and it doesn't have an icon.
