### ISSUE TITLE
Notifications error

### ISSUE THREAD

**Issue by myamusashi** [linkfrg/dotfiles#17]
When running 
notify-send -i /home/gilang/.local/share/icons/Papirus/48x48/apps/org.kde.archUpdate.svg "lakdaj42k34jk" "gg,dlgdflgm"   1 (0.074s) < 20:01:50

i got an error
GDBus.Error:org.freedesktop.DBus.Python.OSError: Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/dbus/service.py", line 712, in _message_cb
    retval = candidate_method(self, *args, **keywords)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gilang/.config/eww/scripts/notifications.py", line 76, in Notify
    self.save_notifications(details)
  File "/home/gilang/.config/eww/scripts/notifications.py", line 182, in save_notifications
    self.write_log_file(current)
  File "/home/gilang/.config/eww/scripts/notifications.py", line 162, in write_log_file
    subprocess.run(["eww", "update", f"notifications={output_json}"])
  File "/usr/lib/python3.11/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.11/subprocess.py", line 1950, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'eww'

**Comment by myamusashi** [comment]
nvm, i just forgot to remove cache files
