### ISSUE TITLE
No menu bar, no application launcher or anything

### ISSUE THREAD

**Issue by nuerocist** [linkfrg/dotfiles#30]
I installed the dotfiles today following the steps but nothing shows up? All the hyprland configs have changed, meaning the keybinds do work but I don't see any sort of menu or application launcher. I installed Ignis normally and it says its running. I cannot figure out the issue
![image](https://github.com/user-attachments/assets/5bd56ada-91ef-4fb1-a9d9-ff8d59c6204e)
![image](https://github.com/user-attachments/assets/da0e2d01-65fe-4075-858f-5f03832ec467)

**Comment by linkfrg** [comment]
Please attach Ignis logs (``~/.ignis/ignis.log``), or type ``ignis quit``, then ``ignis init`` and paste the output from the terminal

**Comment by nuerocist** [comment]
```
(python3:3364): Gtk-WARNING **: 21:42:48.819: Unknown key gtk-modules in /home/nuero/.config/gtk-4.0/settings.ini
2024-10-13 21:42:48 [INFO] Using configuration file: /home/nuero/.config/ignis/config.py
2024-10-13 21:42:49 [ERROR] JSONDecodeError: Unterminated string starting at: line 146 column 20 (char 4094)
Traceback (most recent call last):

  File "/usr/bin/ignis", line 5, in <module>
    main()
    └ <function main at 0x761d01b3e2a0>
  File "/usr/lib/python3.12/site-packages/ignis/main.py", line 12, in main
    cli()
    └ <OrderedGroup cli>
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           │    │     │       └ {}
           │    │     └ ()
           │    └ <function BaseCommand.main at 0x761cfeaaade0>
           └ <OrderedGroup cli>
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         │    │      └ <click.core.Context object at 0x761d01add310>
         │    └ <function MultiCommand.invoke at 0x761cfea78040>
         └ <OrderedGroup cli>
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
           │               │       │       │      └ <click.core.Context object at 0x761d011e7620>
           │               │       │       └ <function Command.invoke at 0x761cfeaab9c0>
           │               │       └ <Command init>
           │               └ <click.core.Context object at 0x761d011e7620>
           └ <function MultiCommand.invoke.<locals>._process_result at 0x761d01b0b100>
  File "/usr/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           │   │      │    │           │   └ {'config': '~/.config/ignis/config.py', 'debug': False}
           │   │      │    │           └ <click.core.Context object at 0x761d011e7620>
           │   │      │    └ <function init at 0x761cf93765c0>
           │   │      └ <Command init>
           │   └ <function Context.invoke at 0x761cfeaaa340>
           └ <click.core.Context object at 0x761d011e7620>
  File "/usr/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
                       │       └ {'config': '~/.config/ignis/config.py', 'debug': False}
                       └ ()
  File "/usr/lib/python3.12/site-packages/ignis/cli.py", line 72, in init
    run_app(config_path, debug)
    │       │            └ False
    │       └ '/home/nuero/.config/ignis/config.py'
    └ <function run_app at 0x761cf91576a0>
  File "/usr/lib/python3.12/site-packages/ignis/app.py", line 432, in run_app
    app.run(None)
    │   └ <function Application.run at 0x761cfea4c400>
    └ <app.IgnisApp object at 0x761cf93c7340 (ignis+app+IgnisApp at 0x576e63b29c00)>
  File "/usr/lib/python3.12/site-packages/gi/overrides/Gio.py", line 42, in run
    return Gio.Application.run(self, *args, **kwargs)
           │   │           │   │      │       └ {}
           │   │           │   │      └ (None,)
           │   │           │   └ <app.IgnisApp object at 0x761cf93c7340 (ignis+app+IgnisApp at 0x576e63b29c00)>
           │   │           └ gi.FunctionInfo(run, bound=None)
           │   └ <class 'gi.repository.Gio.Application'>
           └ <IntrospectionModule 'Gio' from '/usr/lib/girepository-1.0/Gio-2.0.typelib'>
> File "/usr/lib/python3.12/site-packages/ignis/app.py", line 270, in do_activate
    __import__(config_filename)
               └ 'config'

  File "/home/nuero/.config/ignis/config.py", line 8, in <module>
    from modules.bar import bar  # noqa: E402

  File "/home/nuero/.config/ignis/modules/bar/__init__.py", line 2, in <module>
    from .workspaces import workspaces

  File "/home/nuero/.config/ignis/modules/bar/workspaces.py", line 19, in <module>
    hyprland = HyprlandService.get_default()
               │               └ <classmethod(<function BaseService.get_default at 0x761cf9183ce0>)>
               └ <class 'ignis.services.hyprland.service.HyprlandService'>

  File "/usr/lib/python3.12/site-packages/ignis/base_service.py", line 25, in get_default
    cls._instance = cls()
    │   │           └ <class 'ignis.services.hyprland.service.HyprlandService'>
    │   └ None
    └ <class 'ignis.services.hyprland.service.HyprlandService'>
  File "/usr/lib/python3.12/site-packages/ignis/services/hyprland/service.py", line 104, in __init__
    self.__sync_kb_layout()
    └ <service.HyprlandService object at 0x761cf24f4d40 (ignis+services+hyprland+service+HyprlandService at 0x576e652a44d0)>
  File "/usr/lib/python3.12/site-packages/ignis/services/hyprland/service.py", line 159, in __sync_kb_layout
    for kb in json.loads(self.send_command("j/devices"))["keyboards"]:
              │    │     │    └ <function HyprlandService.send_command at 0x761cf1bb3e20>
              │    │     └ <service.HyprlandService object at 0x761cf24f4d40 (ignis+services+hyprland+service+HyprlandService at 0x576e652a44d0)>
              │    └ <function loads at 0x761cf9f89f80>
              └ <module 'json' from '/usr/lib/python3.12/json/__init__.py'>
  File "/usr/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           │                │      └ '{\n"mice": [\n    {\n        "address": "0x5cfa42c22c00",\n        "name": "usb-keyboard-consumer-control-1",\n        "defa...
           │                └ <function JSONDecoder.decode at 0x761cf9f898a0>
           └ <json.decoder.JSONDecoder object at 0x761cfc7bd910>
  File "/usr/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               │    │          │      │  └ '{\n"mice": [\n    {\n        "address": "0x5cfa42c22c00",\n        "name": "usb-keyboard-consumer-control-1",\n        "defa...
               │    │          │      └ <built-in method match of re.Pattern object at 0x761cf9f26740>
               │    │          └ '{\n"mice": [\n    {\n        "address": "0x5cfa42c22c00",\n        "name": "usb-keyboard-consumer-control-1",\n        "defa...
               │    └ <function JSONDecoder.raw_decode at 0x761cf9f89940>
               └ <json.decoder.JSONDecoder object at 0x761cfc7bd910>
  File "/usr/lib/python3.12/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               │    │         │  └ 0
               │    │         └ '{\n"mice": [\n    {\n        "address": "0x5cfa42c22c00",\n        "name": "usb-keyboard-consumer-control-1",\n        "defa...
               │    └ <_json.Scanner object at 0x761cf9f0fa60>
               └ <json.decoder.JSONDecoder object at 0x761cfc7bd910>

json.decoder.JSONDecodeError: Unterminated string starting at: line 146 column 20 (char 4094)
^C2024-10-13 21:43:02 [INFO] Quitting.
```

**Comment by linkfrg** [comment]
Strange, there is shouldn't be this exception. Paste the output from the ``ignis --version`` command

**Comment by linkfrg** [comment]
Should be fixed after linkfrg/ignis@fd6d499 in Ignis repo

You must install ``ignis-git``.

**Comment by nuerocist** [comment]
> Should be fixed after [linkfrg/ignis@fd6d499](https://github.com/linkfrg/ignis/commit/fd6d499) in Ignis repo
> 
> You must install `ignis-git`.

Tried installing git version, got this error code:

```
error: failed to commit transaction (conflicting files)
ignis-git-debug: /usr/lib/debug/usr/lib/ignis/libgvc.so.debug exists in filesystem (owned by ignis-debug)
Errors occurred, no packages were upgraded.
 -> error installing: [/home/nuero/.cache/yay/ignis-git/ignis-git-0.2.r35.g4246898-1-x86_64.pkg.tar.zst /home/nuero/.cache/yay/ignis-git/ignis-git-debug-0.2.r35.g4246898-1-x86_64.pkg.tar.zst] - exit status 1
```

**Comment by nuerocist** [comment]
> Should be fixed after [linkfrg/ignis@fd6d499](https://github.com/linkfrg/ignis/commit/fd6d499) in Ignis repo
> 
> You must install `ignis-git`.

Thanks this fixed it.
